### ISSUE TITLE
Error when trying to import from binance_chain.environment import BinanceEnvironment

### ISSUE THREAD

**Issue by ledzgio** [sammchardy/python-binance-chain#18]
After installing the library on my environment with Python 3.5.3, I try to import the library as follows (in Python shell):

`from binance_chain.environment import BinanceEnvironment`

But I get this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/.local/lib/python3.5/site-packages/binance_chain/environment.py", line 45
    return hash(f"{self.api_url}{self.wss_url}{self.hrp}")
                                                        ^
SyntaxError: invalid syntax
```
Any idea why?

**Comment by ScriptProdigy** [comment]
Hey @ledzgio ,

I had similar issues with secp256k. Had to install the lib properly first.

```
sudo apt-get install lib32ncurses5-dev
sudo add-apt-repository ppa:tah83/secp256k1
sudo apt update
sudo apt install libsecp256k1-dev
```

try this before pip install python-binance-chain

**Comment by ledzgio** [comment]
> Hey @ledzgio ,
> 
> I had similar issues with secp256k. Had to install the lib properly first.
> 
> ```
> sudo apt-get install lib32ncurses5-dev
> sudo add-apt-repository ppa:tah83/secp256k1
> sudo apt update
> sudo apt install libsecp256k1-dev
> ```
> 
> try this before pip install python-binance-chain

It worked, thank you

**Comment by ledzgio** [comment]
@sammchardy is there any chance we get this library compatible with Python 3.5?
